# These are supported funding model platforms

ko_fi: # Replace with a single Ko-fi username
liberapay: # Replace with a single Liberapay username
polar: # Replace with a single Polar username
buy_me_a_coffee: mail+buymeacoffee@pm.albion.onl
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
